version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
  publisher:
    build: './RabbitMQ-publisher'
    ports:
      - '8080'
    expose:
      - '8080'
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
  subscriber:
    build: './RabbitMQ-subscriber'
    ports:
      - '9090'
    expose:
      - '9090'
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - publisher
#    ports:
#      - "4000:4000"